from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Image,
    Table,
    TableStyle,
    KeepTogether
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib.enums import TA_LEFT
from datetime import datetime
from reportlab.lib import colors

styles = getSampleStyleSheet()

# Custom heading style with blue color - larger and more prominent
heading_style = ParagraphStyle(
    "Heading",
    parent=styles["Heading2"],
    fontName="Helvetica-Bold",
    fontSize=16,
    leading=20,
    textColor=colors.HexColor("#1E3A8A"),
    spaceBefore=10,
    spaceAfter=10
)

# Cell style for text wrapping inside tables
cell_style = ParagraphStyle(
    "Cell",
    parent=styles["BodyText"],
    fontName="Helvetica",
    fontSize=9,
    leading=12,
    alignment=TA_LEFT
)

# Common table style with blue colors
table_style = TableStyle([
    ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#EDF4FF")),
    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#8FA8C9")),
    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
    ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
    ("TOPPADDING", (0, 0), (-1, -1), 10),
    ("VALIGN", (0, 0), (-1, -1), "TOP")
])


def add_footer(canvas, doc):
    """
    Add footer with generation info and page number.
    """
    canvas.saveState()
    canvas.setFont("Helvetica-Oblique", 8)
    canvas.drawString(
        20 * mm,
        10 * mm,
        "Generated by AI Resume Screening System"
    )
    canvas.drawRightString(
        190 * mm,
        10 * mm,
        f"Page {doc.page}"
    )
    canvas.restoreState()


def generate_pdf_report(candidate, filename):
    """
    Generates a professional PDF report for a selected candidate.
    """
    doc = SimpleDocTemplate(filename)
    story = []

    # Professional header with logo and title
    logo = Image("assets/logo.png")
    logo.drawHeight = 100
    logo.drawWidth = 100

    header_table = Table(
        [
            [
                logo,
                Paragraph(
                    "<font size=24><b>AI Resume Screening Report</b></font><br/>"
                    f"<font size=10><b>Generated On:</b> "
                    f"{datetime.now().strftime('%d %B %Y, %I:%M %p')}</font>",
                    styles["Normal"]
                )
            ]
        ],
        colWidths=[90, 380]
    )

    header_table.setStyle(
        TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 15)
        ])
    )

    story.append(header_table)
    
    # Add a professional blue divider
    divider_line = Table(
        [[""]],
        colWidths=[470],
        rowHeights=[2]
    )
    divider_line.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#1E3A8A")),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
            ("TOPPADDING", (0, 0), (-1, -1), 0),
        ])
    )
    story.append(divider_line)
    story.append(Paragraph("<br/>", styles["Normal"]))

    # Candidate Information
    candidate_table = Table(
        [
            [Paragraph("<b>Name</b>", cell_style), Paragraph(candidate["Candidate"], cell_style)],
            [Paragraph("<b>Email</b>", cell_style), Paragraph(candidate["Email"], cell_style)],
            [Paragraph("<b>Phone</b>", cell_style), Paragraph(candidate["Phone"], cell_style)]
        ],
        colWidths=[140, 330]
    )
    candidate_table.setStyle(table_style)
    story.append(
        KeepTogether([
            Paragraph("<b>Candidate Information</b>", heading_style),
            candidate_table
        ])
    )
    story.append(Paragraph("<br/>", styles["Normal"]))

    # Education
    education_table = Table(
        [
            [Paragraph("<b>Degree</b>", cell_style), Paragraph(candidate["Degree"], cell_style)],
            [Paragraph("<b>Branch</b>", cell_style), Paragraph(candidate["Branch"], cell_style)],
            [Paragraph("<b>University</b>", cell_style), Paragraph(candidate["University/College"], cell_style)],
            [Paragraph("<b>Graduation Year</b>", cell_style), Paragraph(candidate["Graduation Year"], cell_style)],
            [Paragraph("<b>CGPA</b>", cell_style), Paragraph(candidate["CGPA"], cell_style)]
        ],
        colWidths=[140, 330]
    )
    education_table.setStyle(table_style)
    story.append(
        KeepTogether([
            Paragraph("<b>Education</b>", heading_style),
            education_table
        ])
    )
    story.append(Paragraph("<br/>", styles["Normal"]))

    # Performance Scores
    performance_table = Table(
        [
            [Paragraph("<b>ATS Score</b>", cell_style), Paragraph(f"{candidate['ATS Score']:.2f}%", cell_style)],
            [Paragraph("<b>Semantic Score</b>", cell_style), Paragraph(f"{candidate['Semantic Score']:.2f}%", cell_style)],
            [Paragraph("<b>Skill Match</b>", cell_style), Paragraph(f"{candidate['Skill Match (%)']:.2f}%", cell_style)],
            [Paragraph("<b>Experience</b>", cell_style), Paragraph(f"{candidate['Experience (Years)']} Years", cell_style)]
        ],
        colWidths=[140, 330]
    )
    performance_table.setStyle(table_style)
    story.append(
        KeepTogether([
            Paragraph("<b>Performance Scores</b>", heading_style),
            performance_table
        ])
    )
    story.append(Paragraph("<br/>", styles["Normal"]))

    # Skills Analysis
    skills_table = Table(
        [
            [Paragraph("<b>Matched Skills</b>", cell_style), Paragraph(candidate["Matched Skills"], cell_style)],
            [Paragraph("<b>Missing Skills</b>", cell_style), Paragraph(candidate["Missing Skills"], cell_style)]
        ],
        colWidths=[140, 330]
    )
    skills_table.setStyle(table_style)
    story.append(
        KeepTogether([
            Paragraph("<b>Skills Analysis</b>", heading_style),
            skills_table
        ])
    )
    story.append(Paragraph("<br/>", styles["Normal"]))

    # AI Candidate Summary
    summary_table = Table(
        [
            [Paragraph(candidate["Summary"], cell_style)]
        ],
        colWidths=[450]
    )
    summary_table.setStyle(
        TableStyle([
            ("BOX", (0, 0), (-1, -1), 0.7, colors.HexColor("#8FA8C9")),
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFD")),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
            ("TOPPADDING", (0, 0), (-1, -1), 10),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
            ("VALIGN", (0, 0), (-1, -1), "TOP")
        ])
    )
    story.append(
        KeepTogether([
            Paragraph("<b>AI Candidate Summary</b>", heading_style),
            summary_table
        ])
    )
    story.append(Paragraph("<br/>", styles["Normal"]))

    # Hiring Recommendation
    recommendation_table = Table(
        [
            [Paragraph("Recommendation generated in the application based on ATS Score.", cell_style)]
        ],
        colWidths=[450]
    )
    recommendation_table.setStyle(
        TableStyle([
            ("BOX", (0, 0), (-1, -1), 0.7, colors.HexColor("#8FA8C9")),
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFD")),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
            ("TOPPADDING", (0, 0), (-1, -1), 10),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
            ("VALIGN", (0, 0), (-1, -1), "TOP")
        ])
    )
    story.append(
        KeepTogether([
            Paragraph("<b>Hiring Recommendation</b>", heading_style),
            recommendation_table
        ])
    )

    # Build PDF with footer
    doc.build(
        story,
        onFirstPage=add_footer,
        onLaterPages=add_footer
    )
