from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet

styles = getSampleStyleSheet()


def generate_pdf_report(candidate, filename):
    """
    Generates a PDF report for a selected candidate.
    """

    doc = SimpleDocTemplate(filename)

    story = []

    story.append(
    Paragraph(
        "<b><font size=18>AI Resume Screening Report</font></b>",
        styles["Title"]
        )
    )

    story.append(Paragraph("<br/><br/>", styles["Normal"]))

    story.append(
    Paragraph("<b>Candidate Information</b>", styles["Heading2"])
    )

    story.append(
        Paragraph(f"<b>Name:</b> {candidate['Candidate']}", styles["Normal"])
    )

    story.append(
        Paragraph(f"<b>Email:</b> {candidate['Email']}", styles["Normal"])
    )

    story.append(
        Paragraph(f"<b>Phone:</b> {candidate['Phone']}", styles["Normal"])
    )

    story.append(
        Paragraph("<br/>", styles["Normal"])
    )

    story.append(
        Paragraph("<b>Education</b>", styles["Heading2"])
    )

    story.append(
        Paragraph(
            f"<b>Degree:</b> {candidate['Degree']}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Branch:</b> {candidate['Branch']}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>University/College:</b> {candidate['University/College']}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Graduation Year:</b> {candidate['Graduation Year']}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>CGPA:</b> {candidate['CGPA']}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph("<br/>", styles["Normal"])
    )

    story.append(
        Paragraph("<b>Performance Scores</b>", styles["Heading2"])
    )

    story.append(
        Paragraph(
            f"<b>ATS Score:</b> {candidate['ATS Score']}%",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Semantic Score:</b> {candidate['Semantic Score']}%",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Skill Match:</b> {candidate['Skill Match (%)']}%",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Experience:</b> {candidate['Experience (Years)']} Years",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph("<br/>", styles["Normal"])
    )

    story.append(
    Paragraph("<b>Skills Analysis</b>", styles["Heading2"])
    )

    story.append(
        Paragraph(
            f"<b>Matched Skills:</b> {candidate['Matched Skills']}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Missing Skills:</b> {candidate['Missing Skills']}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph("<br/>", styles["Normal"])
    )

    story.append(
        Paragraph("<b>AI Candidate Summary</b>", styles["Heading2"])
    )

    story.append(
        Paragraph(
            candidate["Summary"],
            styles["Normal"]
        )
    )

    story.append(
        Paragraph("<br/>", styles["Normal"])
    )

    story.append(
    Paragraph("<b>Hiring Recommendation</b>", styles["Heading2"])
    )

    story.append(
        Paragraph(
            "Recommendation generated in the application based on ATS Score.",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph("<br/>", styles["Normal"])
    )

    story.append(
        Paragraph(
            "<br/><br/><i>Generated by AI Resume Screening System</i>",
            styles["Normal"]
        )
    )

    doc.build(story)