from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Image,
    Table,
    TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime
from reportlab.lib import colors

styles = getSampleStyleSheet()


def generate_pdf_report(candidate, filename):
    """
    Generates a PDF report for a selected candidate.
    """

    doc = SimpleDocTemplate(filename)

    story = []

    logo = Image("assets/logo.png")

    logo.drawHeight = 100
    logo.drawWidth = 100
    
    story.append(logo)
    
    story.append(
        Paragraph("<br/>", styles["Normal"])
    )

    story.append(
        Paragraph(
            "<b><font size=18>AI Resume Screening Report</font></b>",
            styles["Title"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Generated On:</b> {datetime.now().strftime('%d %B %Y, %I:%M %p')}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph("<b>Candidate Information</b>", styles["Heading2"])
    )

    candidate_table = Table(
        [
            ["Name", candidate["Candidate"]],
            ["Email", candidate["Email"]],
            ["Phone", candidate["Phone"]]
        ],
        colWidths=[150, 300]
    )

    candidate_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
            ("GRID", (0, 0), (-1, -1), 1, colors.black),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE")
        ])
    )

    story.append(candidate_table)

    story.append(
        Paragraph("<br/>", styles["Normal"])
    )

    story.append(
        Paragraph("<b>Education</b>", styles["Heading2"])
    )

    education_table = Table(
        [
            ["Degree", candidate["Degree"]],
            ["Branch", candidate["Branch"]],
            ["University", candidate["University/College"]],
            ["Graduation Year", candidate["Graduation Year"]],
            ["CGPA", candidate["CGPA"]]
        ],
        colWidths=[150, 300]
    )

    education_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
            ("GRID", (0, 0), (-1, -1), 1, colors.black),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE")
        ])
    )

    story.append(education_table)

    story.append(
        Paragraph("<br/>", styles["Normal"])
    )

    story.append(
        Paragraph("<b>Performance Scores</b>", styles["Heading2"])
    )

    performance_table = Table(
        [
            ["ATS Score", f"{candidate['ATS Score']}%"],
            ["Semantic Score", f"{candidate['Semantic Score']}%"],
            ["Skill Match", f"{candidate['Skill Match (%)']}%"],
            ["Experience", f"{candidate['Experience (Years)']} Years"]
        ],
        colWidths=[150, 300]
    )

    performance_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
            ("GRID", (0, 0), (-1, -1), 1, colors.black),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE")
        ])
    )

    story.append(performance_table)

    story.append(
        Paragraph("<br/>", styles["Normal"])
    )

    story.append(
    Paragraph("<b>Skills Analysis</b>", styles["Heading2"])
    )

    story.append(
        Paragraph(
            f"<b>Matched Skills:</b> {candidate['Matched Skills']}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Missing Skills:</b> {candidate['Missing Skills']}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph("<br/>", styles["Normal"])
    )

    story.append(
        Paragraph("<b>AI Candidate Summary</b>", styles["Heading2"])
    )

    story.append(
        Paragraph(
            candidate["Summary"],
            styles["Normal"]
        )
    )

    story.append(
        Paragraph("<br/>", styles["Normal"])
    )

    story.append(
    Paragraph("<b>Hiring Recommendation</b>", styles["Heading2"])
    )

    story.append(
        Paragraph(
            "Recommendation generated in the application based on ATS Score.",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph("<br/>", styles["Normal"])
    )

    story.append(
        Paragraph(
            "<br/><br/><i>Generated by AI Resume Screening System</i>",
            styles["Normal"]
        )
    )

    doc.build(story)